version: "3.1"
services:
  ydl_api_ng:
    container_name: ydl_api_ng
    image: totonyus/ydl_api_ng
    restart: unless-stopped
    ports:
      - 5011:80
    volumes:
      - ./params:/app/params
      - ./logs:/app/logs
      - ./downloads:/app/downloads
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UID=1000
      - GID=1000
      - NB_WORKERS=5
      - LOG_LEVEL=error
      # Redis will be disable is this value is not false, remember to also change the setting in params.ini file
      - DISABLE_REDIS=false
